"""Prometheus metrics instrumentation for convoy-brain.

Exports metrics for:
- LLM token generation speed and inference latency
- MCP tool execution latency and error rates
- API endpoint request duration and status codes
- Orchestrator reasoning loop detection
"""

from __future__ import annotations

import time
from contextlib import asynccontextmanager
from typing import AsyncIterator

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    Info,
    generate_latest,
    CONTENT_TYPE_LATEST,
)

# ─── LLM / Ollama Metrics ────────────────────────────────────────

LLM_TOKENS_GENERATED = Counter(
    "vvip_llm_tokens_generated_total",
    "Total tokens generated by Qwen LLM",
    ["model"],
)

LLM_INFERENCE_DURATION = Histogram(
    "vvip_llm_inference_duration_seconds",
    "LLM inference latency in seconds",
    ["model"],
    buckets=[0.5, 1, 2, 5, 10, 15, 20, 30, 45, 60, 90, 120],
)

OLLAMA_HEALTH = Gauge(
    "vvip_ollama_health_up",
    "Whether Ollama API is reachable (1=up, 0=down)",
)

LLM_TOKENS_PER_SEC = Gauge(
    "vvip_llm_tokens_per_second",
    "Current LLM token generation rate",
    ["model"],
)

# ─── MCP Tool Metrics ────────────────────────────────────────────

MCP_TOOL_CALLS = Counter(
    "vvip_mcp_tool_calls_total",
    "Total MCP tool invocations",
    ["tool_name"],
)

MCP_TOOL_DURATION = Histogram(
    "vvip_mcp_tool_duration_seconds",
    "MCP tool execution latency",
    ["tool_name"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30],
)

MCP_TOOL_ERRORS = Counter(
    "vvip_mcp_tool_errors_total",
    "MCP tool execution errors",
    ["tool_name", "error"],
)

# ─── API Metrics ──────────────────────────────────────────────────

API_REQUEST_DURATION = Histogram(
    "vvip_api_request_duration_seconds",
    "API request duration",
    ["service", "method", "endpoint", "status"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30],
)

API_REQUESTS_TOTAL = Counter(
    "vvip_api_requests_total",
    "Total API requests",
    ["service", "method", "endpoint", "status"],
)

# ─── Orchestrator Metrics ─────────────────────────────────────────

ORCHESTRATOR_TOOL_ROUNDS = Gauge(
    "vvip_orchestrator_tool_rounds_total",
    "Number of tool rounds in current/last orchestrator turn",
    ["movement_id"],
)

ORCHESTRATOR_NONDETERMINISTIC_ERRORS = Counter(
    "vvip_orchestrator_nondeterministic_errors_total",
    "Non-deterministic failures (different output for same input)",
)

ORCHESTRATOR_TURNS = Counter(
    "vvip_orchestrator_turns_total",
    "Total orchestrator turns",
    ["workflow"],
)

# ─── Build Info ───────────────────────────────────────────────────

BUILD_INFO = Info(
    "vvip_convoy_brain",
    "Build information for convoy-brain service",
)
BUILD_INFO.info({
    "version": "1.0.0",
    "service": "convoy-brain",
    "model": "qwen3.5:9b-q4_K_M",
})


# ─── Helper Decorators ───────────────────────────────────────────

@asynccontextmanager
async def track_llm_call(model: str = "qwen3.5:9b-q4_K_M") -> AsyncIterator[dict]:
    """Context manager that tracks LLM call duration and token count.

    Usage:
        async with track_llm_call() as tracker:
            response = await ollama.generate(prompt)
            tracker["tokens"] = response.eval_count
    """
    tracker: dict = {"tokens": 0}
    start = time.monotonic()
    try:
        yield tracker
    finally:
        duration = time.monotonic() - start
        LLM_INFERENCE_DURATION.labels(model=model).observe(duration)
        tokens = tracker.get("tokens", 0)
        if tokens > 0:
            LLM_TOKENS_GENERATED.labels(model=model).inc(tokens)
            if duration > 0:
                LLM_TOKENS_PER_SEC.labels(model=model).set(tokens / duration)


@asynccontextmanager
async def track_mcp_tool(tool_name: str) -> AsyncIterator[None]:
    """Context manager that tracks MCP tool call duration and errors."""
    MCP_TOOL_CALLS.labels(tool_name=tool_name).inc()
    start = time.monotonic()
    try:
        yield
    except TimeoutError:
        MCP_TOOL_ERRORS.labels(tool_name=tool_name, error="timeout").inc()
        raise
    except Exception as e:
        MCP_TOOL_ERRORS.labels(tool_name=tool_name, error=type(e).__name__).inc()
        raise
    finally:
        duration = time.monotonic() - start
        MCP_TOOL_DURATION.labels(tool_name=tool_name).observe(duration)


def record_api_request(
    method: str, endpoint: str, status: int, duration: float
) -> None:
    """Record API request metrics."""
    labels = {
        "service": "convoy-brain",
        "method": method,
        "endpoint": endpoint,
        "status": str(status),
    }
    API_REQUEST_DURATION.labels(**labels).observe(duration)
    API_REQUESTS_TOTAL.labels(**labels).inc()


def get_metrics_response() -> tuple[bytes, str]:
    """Generate Prometheus metrics response."""
    return generate_latest(), CONTENT_TYPE_LATEST
